version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    versioning-strategy: "auto"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
    commit-message:
      prefix: "fix"
      include: "scope"
    ignore:
      # These packages are managed by React Scripts
      - dependency-name: "webpack"
      - dependency-name: "babel*"
    groups:
      dev-dependencies:
        patterns:
          - "*eslint*"
          - "*prettier*"
          - "*jest*" 